version: "3.7"

services:

  # PHP FPM
  php-fpm:
    build: './docker/php-fpm'
    container_name: procure_php-fpm
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=symfony-demo"
    volumes:
      - ./:/var/www/app
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/app
    links:
      - mysql


  # Nginx
  nginx:
    image: nginx:1.15
    container_name: procure_nginx
    volumes:
      - ./:/var/www/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www/app
    expose:
      - "10090"
    ports:
      - 8080:80
    depends_on:
      - php-fpm
      - mysql

  # MySQL
  mysql:
    image: mysql:5.7
    container_name: procure_mysql
    command: mysqld --sql_mode="STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./var/mysql:/var/lib/mysql
      - ./docker/etc/mysql/my.conf:/etc/mysql/my.cnf
      - ./mysql-dump:/docker-entrypoint-initdb.d
    ports:
      - 3309:3306
    env_file:
      - '.env.local'
